
import Footer from "./components/Footer";
import { AuthProvider } from "./lib/AuthContext";
import "./globals.css";

export const metadata = {
  title: "A23Satta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">    
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Mona+Sans:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" ></link>
      </head> 
      <body >
        <AuthProvider>
        {children}
         <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
